### ISSUE TITLE
FastQC install failed

### ISSUE THREAD

**Issue by SylGuib** [Miachol/doc-BioInstaller#1]
The installation of FastQC fails because URL is incorrect.
Otherwise, this a very convenient package !!

**Comment by Miachol** [comment]
It seems that the FastQC official homepage have been changed from "http://www.bioinformatics.bbsrc.ac.uk/projects/fastqc/" to "http://www.bioinformatics.babraham.ac.uk/projects/fastqc/"
I will modified that in next release version.
Thanks.

**Comment by SylGuib** [comment]
Would you have an idea of a date for the next release ?
Best regards,

Sylvain

*Sylvain Guibert, PhD*
Bioinformatician, GeCo consultant

*INTEGRAGEN*
Genopole Campus 1 ­| Genavenir 8
5 rue Henri Desbruères | ­91000 EVRY | France
Phone :+ 33 (0)1 60 910 919
sylvain.guibert@integragen.com
*VISIT OUR NEW WEBSITE dedicated to genomic
services:​​ http://www.integragen-genomics.com
<http://www.integragen-genomics.com/>*

2017-04-24 14:06 GMT+02:00 Li Jianfeng <notifications@github.com>:

**Comment by Miachol** [comment]
I will fix that bug in github today; Next release will be upload to CRAN tomorrow. 
Best wishes
